In [1]:
import numpy as np 
import pandas as pd

In [3]:
job_Roledata = pd.read_csv("roo_data.csv")

In [4]:
job_Roledata

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,69,63,78,87,94,94,87,84,61,9,...,Prayer books,salary,no,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,78,62,73,60,71,70,73,84,91,12,...,Childrens,salary,yes,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,71,86,91,87,61,81,72,72,94,11,...,Travel,Work,no,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,76,87,60,84,89,73,62,88,69,7,...,Romance,Work,yes,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,92,62,90,67,71,89,73,71,73,4,...,Cookbooks,salary,no,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,83,67,62,63,81,74,90,84,69,4,...,Journals,Work,yes,stubborn,Management,salary,smart worker,yes,no,Technical Engineer
19996,80,69,83,87,82,66,66,92,67,7,...,Cookbooks,salary,no,stubborn,Management,salary,hard worker,no,yes,E-Commerce Analyst
19997,83,70,80,87,64,85,69,94,88,7,...,Drama,Work,yes,gentle,Technical,work,hard worker,no,yes,Business Intelligence Analyst
19998,68,87,91,88,66,74,61,87,61,5,...,Travel,Work,no,gentle,Management,work,smart worker,yes,no,Software Quality Assurance (QA) / Testing
19999,73,77,74,84,70,65,92,73,90,7,...,Comics,Work,no,gentle,Management,work,hard worker,yes,no,Applications Developer

In [5]:
object_Columns = job_Roledata.select_dtypes(include=['object']).copy()

In [6]:
print("dhape of only object data",object_Columns.shape)

dhape of only object data (20000, 25)

In [7]:
object_Columns.drop(['Suggested Job Role'], axis = 1, inplace = True)

In [8]:
print("dhape of only object data",object_Columns.shape)

dhape of only object data (20000, 24)

In [11]:
from sklearn.preprocessing import OneHotEncoder
le = OneHotEncoder()
object_Columns= le.fit_transform(object_Columns)

In [14]:
print(object_Columns)

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 5)	1.0
  (0, 14)	1.0
  (0, 15)	1.0
  (0, 23)	1.0
  (0, 26)	1.0
  (0, 27)	1.0
  (0, 30)	1.0
  (0, 37)	1.0
  (0, 47)	1.0
  (0, 49)	1.0
  (0, 59)	1.0
  (0, 61)	1.0
  (0, 63)	1.0
  (0, 86)	1.0
  (0, 97)	1.0
  (0, 98)	1.0
  (0, 101)	1.0
  (0, 102)	1.0
  (0, 104)	1.0
  (0, 106)	1.0
  (0, 109)	1.0
  (0, 110)	1.0
  (1, 1)	1.0
  :	:
  (19998, 110)	1.0
  (19999, 1)	1.0
  (19999, 3)	1.0
  (19999, 5)	1.0
  (19999, 6)	1.0
  (19999, 17)	1.0
  (19999, 23)	1.0
  (19999, 26)	1.0
  (19999, 27)	1.0
  (19999, 30)	1.0
  (19999, 34)	1.0
  (19999, 48)	1.0
  (19999, 50)	1.0
  (19999, 53)	1.0
  (19999, 62)	1.0
  (19999, 63)	1.0
  (19999, 71)	1.0
  (19999, 96)	1.0
  (19999, 98)	1.0
  (19999, 100)	1.0
  (19999, 102)	1.0
  (19999, 105)	1.0
  (19999, 106)	1.0
  (19999, 109)	1.0
  (19999, 110)	1.0

In [13]:
uk_Classifier = models.Sequential()
#Input layer 
uk_Classifier.add(Dense(units = 50, activation = 'relu',input_shape=(38, )))
#hideen layer
uk_Classifier.Dropout(0.3, noise_shape=None, seed=None)
uk_Classifier.add(Dense(units = 3, activation = 'relu'))
uk_Classifier.add(Dense(units = 1, activation = 'softmax'))

AttributeError: iloc not found

In [ ]:
object_Columns